site_name: Isra's Engineering Notes
site_description: Personal knowledge base — data engineering, infra, tools
dev_addr: 127.0.0.1:8003

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.top
    - navigation.indexes
    - navigation.tracking
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: blue
      accent: blue

plugins:
  - search
  - blog:
      blog_dir: blog
      post_date_format: long
      post_url_format: "{date}/{slug}"
      archive: false
      categories: true
      categories_name: Topics
      categories_url_format: "topic/{slug}"
      categories_allowed:
        - Data Engineering
        - Homelab
        - Tooling

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Blog:
    - blog/index.md
  - TIL: til/index.md

