site_name: GWS Documentation
site_url: https://blog.gws.my.id

nav:
  - Home: index.md
  - Supervisor Manager:
    - Overview: supervisor_manager/overview.md

theme:
  name: material
  features:
    - navigation.expand
    - content.tabs.link
  palette:
    primary: 'blue'
    accent: 'indigo'
    icon: '🚀'

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.inlinehilite

plugins:
  - search